DayOut/Models/DisplayRouteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DayOut.Models
{
    public class DisplayRouteViewModel
    {
        public List<Place> Places { get; set; }
        public List<string> Addresses { get; set; }
        public List<string> Times { get; set; }
        public string GoogleAPI { get; set; }
        public List<string> PlaceLetters { get; set; }
    }
}

DayOut/Controllers/RandomizedDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using DayOut.Class;
using DayOut.Data;
using DayOut.Data.Migrations;
using DayOut.Models;
using GoogleCategories;
using GooglePlaceDetails;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DayOut.Controllers
{
    public class RandomizedDayController : Controller
    {
        public ApplicationDbContext db;

        //private readonly ApplicationDbContext _context;

        public RandomizedDayController(ApplicationDbContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return RedirectToAction("SelectStartEndTime");
        }

        public IActionResult SelectStartEndTime()
        {
            Customer customer = new Customer() { RandStartTime = 0800, RandEndTime = 1300 };
            SelectTimesViewModel selectTimesViewModel = new SelectTimesViewModel() { Customer = customer };
            DateTime currentTime = DateTime.Now;
            string militaryTime = currentTime.ToString("HHmm");
            int currentMilTime = Convert.ToInt32(militaryTime);
            ViewData["Time"] = new SelectList(db.Times.Where(t => t.MilitaryTime > currentMilTime - 100), "Id", "StandardTime");
            return View(selectTimesViewModel);
        }
        [HttpPost]
        public IActionResult SelectStartEndTime(SelectTimesViewModel selectTimesViewModel)
        {
            int startTime = db.Times.Where(t => t.Id == selectTimesViewModel.Customer.RandStartTime).Select(t => t.MilitaryTime).Single();
            int endTime = db.Times.Where(t => t.Id == selectTimesViewModel.Customer.RandEndTime).Select(t => t.MilitaryTime).Single();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customerToUpdate = db.Customers.Where(c => c.UserId == userId).Single();
            customerToUpdate.RandEndTime = endTime;
            customerToUpdate.RandStartTime = startTime;
            customerToUpdate.TimeLeft = TimeCalculations.FindTimeSpan(startTime, endTime);
            db.SaveChanges();
            return RedirectToAction("RetrieveData");
        }

        public IActionResult RetrieveData(int endGoTo = 0)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            List<CategoryPlaces> availableCategories = GetCategoriesAvailable.CategoriesAvailable(customer);
            List<Tuple<List<PlaceDetails>, string>> data = GetAllDetails.ReplaceWithDetails(availableCategories);
            List<Tuple<List<PlaceDetails>, string>> finalData = FilterPlacesOpen.ReturnFilteredPlaces(data, customer.RandStartTime, customer.RandEndTime);
            List<string> categories = SetAllCategories.FindAllCategories(finalData);
            SetCategoriesTable(categories);
            TruncateSelectedTable();
            if (endGoTo == 0)
            {
                return RedirectToAction("SelectCategories");
            }
            else
            {
                //Redirect to show route
                return RedirectToAction("SelectCategories");
            }
        }
        private void TruncateSelectedTable()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE [SelectedCategories]");
        }
        private void TruncatePlacesTable()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            List<Place> customerPlaces = db.Places.Where(p => p.CustomerId == customer.Id).ToList();
            foreach (Place place in customerPlaces)
            {
                db.Places.Remove(place);
                db.SaveChanges();
            }
        }

        private void SetCategoriesTable(List<string> availableCategories)
        {
            List<Category> allCategories = db.Categories.ToList();
            bool fired = false;
            foreach (Category category in allCategories)
            {
                foreach (string name in availableCategories)
                {
                    if (category.Name == name)
                    {
                        category.IsAvailable = true;
                        db.SaveChanges();
                        fired = true;
                        break;
                    }
                }
                if (fired != true)
                {
                    category.IsAvailable = false;
                    db.SaveChanges();
                }
                fired = false;
            }
        }

        //GET
        public IActionResult SelectCategories(string selected = "")
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            if (selected != "")
            {
                SelectedCategory selectedCategory = new SelectedCategory() { Name = selected };
                db.SelectedCategories.Add(selectedCategory);
                Category category = db.Categories.Where(c => c.Name == selected).Single();
                if (category.Name != "Restaurant")
                {
                    category.IsAvailable = false;
                }
                customer.TimeLeft -= category.TimeToDo;
                db.SaveChanges();
            }
            SelectCategoriesViewModel selectCategoriesViewModel = new SelectCategoriesViewModel();
            selectCategoriesViewModel.Categories = db.Categories.Where(c => c.IsAvailable == true && c.TimeToDo <= customer.TimeLeft).Select(c => c.Name).ToList();
            selectCategoriesViewModel.Selected = db.SelectedCategories.Select(c => c.Name).ToList();
            ViewBag.TimeLeft = customer.TimeLeft < 50 ? false : true;
            ViewBag.OptionsLeft = selectCategoriesViewModel.Categories.Count > 0 ? true : false;
            ViewBag.HasSelected = selectCategoriesViewModel.Selected.Count > 0 ? true : false;
            return View(selectCategoriesViewModel);
        }
        public IActionResult BuildRoute()
        {
            SetPlaces();

            return RedirectToAction("DisplayRoute");
        }

        private void SetPlaces()
        {
            List<string> selectedCategories = db.SelectedCategories.Select(c => c.Name).ToList();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            List<CategoryPlaces> availableCategories = GetCategoriesAvailable.CategoriesAvailable(customer, selectedCategories);
            List<Tuple<List<PlaceDetails>, string>> data = GetAllDetails.ReplaceWithDetails(availableCategories);
            List<Tuple<List<PlaceDetails>, string>> finalData = FilterPlacesOpen.ReturnFilteredPlaces(data, customer.RandStartTime, customer.RandEndTime);
            TruncatePlacesTable();
            Random random = new Random();
            foreach (Tuple<List<PlaceDetails>, string> category in finalData)
            {
                PlaceDetails place = category.Item1[RandomInstance.RandomNumber(0, category.Item1.Count)];
                Place newPlace = new Place()
                {
                    Name = place.Result.Name,
                    PriceLevel = 0,
                    Category = category.Item2,
                    Latitude = place.Result.Geometry.Location.Lat,
                    Longitude = place.Result.Geometry.Location.Lng,
                    PlaceId = place.Result.PlaceId,
                    CustomerId = customer.Id
                };
                string error = "Not Provided";
                try
                {
                    newPlace.PhoneNumber = place.Result.FormattedPhoneNumber;
                }
                catch
                {
                    newPlace.PhoneNumber = error;
                }
                try
                {
                    newPlace.Address = place.Result.FormattedAddress;
                }
                catch
                {
                    newPlace.Address = error;
                }
                try
                {
                    newPlace.Rating = place.Result.Rating;
                }
                catch
                {
                    newPlace.Rating = 0;
                }
                db.Places.Add(newPlace);
                db.SaveChanges();
            }
        }

        public IActionResult DisplayRoute(bool fromSelect = true)
        {
            if (fromSelect)
            {
                SetPlaces();
            }
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            if (fromSelect == false)
            {
                if (customer.HasRoute == false)
                {
                    return RedirectToAction("Index", "Home", new { hasroute = false });
                }
            }
            DisplayRouteViewModel displayRoute = new DisplayRouteViewModel();
            displayRoute.Places = db.Places.Where(p => p.CustomerId == customer.Id).ToList();
            displayRoute.Addresses = new List<string>();
            displayRoute.GoogleAPI = APIKey.GoogleAPI;
            foreach (Place place in displayRoute.Places)
            {
                displayRoute.Addresses.Add(place.Address);
            }

DayOut/Views/RandomizedDay/DisplayRoute.cshtml
@model DayOut.Models.DisplayRouteViewModel
@{
    ViewData["Title"] = "DisplayRoute";
}


<!--The div element for the map -->

<style>
    #map {
        height: 800px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }
    .table_scroll {
        width: 100%;
        overflow-y: scroll;
        border-collapse: collapse;
        border-spacing: 0;
        height: 230px;
        display: block;
    }
    #rcorners2 {
        border-radius: 25px;
        border: 2px solid black;
        padding: 20px;
    }
</style>
<div class="row" style="padding-top:1em">
    <div class="col-md-4">
        <center>
            <div>
                <table class="table_scroll" style="height:650px;">
                    @for (int i = 0; i < Model.Places.Count; i++)
                    {
                        <tr>
                            <td style=" padding-top:1em; padding-right:1em">
                                <div class="row" style="padding-right:1em">
                                    <div class="col-md-2" style="padding:0.5em">
                                        <center>
                                            <h3><strong>@Html.Raw(Model.PlaceLetters[i])</strong></h3>
                                        </center>
                                    </div>
                                    <div class="col-md-10" id="rcorners2" style="padding:0.5em">
                                        <span style="font-size:25px"><strong>@Html.Raw(Model.Places[i].Name)</strong></span>
                                        <br />
                                        <span style="font-size:15px">Address: @Html.Raw(Model.Places[i].Address)</span>
                                        <br />
                                        <span style="font-size:15px">Phone: @Html.Raw(Model.Places[i].PhoneNumber)</span>
                                        <br />
                                        <span style="font-size:15px">Rating: @Html.Raw(Model.Places[i].Rating)</span>
                                    </div>
                                </div>

                            </td>
                        </tr>
                    }
                </table>
            </div>
        </center>
    </div>
    <div class="col-md-8">
        <center>
            <div>
                <div id="map"  style="height:650px;"></div>
            </div>
        </center>
    </div>
</div>

<div hidden>
    <div>
        <select id="start">
            <option value=@Html.Raw(Model.Addresses[0])>Halifax, NS</option>
        </select>
        <select multiple id="waypoints">
            @for (int i = 1; i < Model.Addresses.Count - 1; i++)
            {
                <option value=@Html.Raw(Model.Addresses[i])></option>
            }
        </select>
        <select id="end">
            <option value=@Html.Raw(Model.Addresses[Model.Addresses.Count - 1])>Vancouver, BC</option>
        </select>
    </div>
    <div id="directions-panel"></div>
</div>

<script type="text/javascript">
    function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 6,
            center: { lat: 41.85, lng: -87.65 }
        });
        directionsDisplay.setMap(map);
        calculateAndDisplayRoute(directionsService, directionsDisplay);
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        @*var pre = '@Html.Raw(Json.Serialize(Model.Addresses))';
        var checkboxArrayTest = JSON.parse(pre);
        var checkboxArrayHard = ["montreal, quebec", "toronto, ont"];*@
        var checkboxArray = document.getElementById('waypoints');;
        for (var i = 0; i < checkboxArray.length; i++) {
            waypts.push({
                location: checkboxArray[i].value,
                stopover: true
            });

        }

        directionsService.route({
            origin: document.getElementById('start').value,
            destination: document.getElementById('end').value,
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: 'DRIVING'
        }, function (response, status) {
            if (status === 'OK') {
                directionsDisplay.setDirections(response);
                var route = response.routes[0];
                var summaryPanel = document.getElementById('directions-panel');
                summaryPanel.innerHTML = '';
                 //For each route, display summary information.
                //for (var i = 0; i < route.legs.length; i++) {
                //    var routeSegment = i + 1;
                //    summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                //        '</b><br>';
                //    summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                //    summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                //    summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                //}
            } else {
                window.alert('Directions request failed due to ' + status);
            }
        }
                );
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCm51Yofz7jCEmtkvN4mFady9iETRhqm_s&callback=initMap">
</script>

DayOut/Views/RandomizedDay/LoadingGif.cshtml

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container" style="padding-top:10em; width:30% ">
    <div class="row">
        <div class="col-sm-12">
            <div class="modal-content" style="background-color:#f6f5f3; border-radius:75px">
                <div class="modal-header" style="background-color:#f6f5f3; border-radius:75px">
                    <center>
                        <h4 class="modal-title" id="myModal" style="padding-top:20px">Finding Open Places Near You</h4>
                    </center>
                    <div>
                        <div class="modal-body" style="background-color:#f6f5f3; border-radius:75px">
                            <center>
                                <div>
                                    <img  style="height:15em; width:15em" src="https://cdn-images-1.medium.com/max/1600/0*smsSMhaW2J5RgY8G.gif" />
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DayOut/Views/RandomizedDay/SelectCategories.cshtml
@model DayOut.Models.SelectCategoriesViewModel
@{
    ViewData["Title"] = "SelectCategories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div style="padding-top:3em">
    <center>
        @if (ViewBag.HasSelected == true)
        {
            <h2>Selected Categories</h2>
            <hr />
            <table>
                <tr></tr>
                @foreach (var item in Model.Selected)
                {
                    if (item != null)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-default btn-large" style="width:500px">@Html.Raw(item)</button>
                            </td>

                        </tr>
                    }
                }
            </table>
        }
        @if (ViewBag.TimeLeft == false)
        {
            <div>
                <h3 style="color:red">You are out of time.</h3>
            </div>
        }
        @if (ViewBag.TimeLeft == true && ViewBag.OptionsLeft == true)
        {
            <h2>Select a Category</h2>
            <hr />
            <div>
                <table>
                    <tr></tr>
                    @foreach (var item in Model.Categories)
                    {
                        if (item != null)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(item, "SelectCategories", "RandomizedDay", new { selected = item }, new { @class = "btn btn-primary btn-large", style = "width:200px" })
                                </td>
                            </tr>
                        }
                    }
                </table>
                <div hidden>
                    @Html.EditorFor(model => model.Categories)
                </div>
            </div>
        }
        <div>
            <br />
            @if (ViewBag.OptionsLeft == false)
            {
                <div class="row">
                    <div class="col-md-6">
                        <div style="float:right">
                            <button class="btn btn-success btn-large" id="Show_Options" style="width:200px">Build Route</button>
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div style="float:left">
                            @Html.ActionLink("Restart", "SelectStartEndTime", "RandomizedDay", null, new { @class = "btn btn-primary btn-large", style = "width:200px" })
                        </div>
                    </div>
                </div>
            }
            else
            {
                <button class="btn btn-success btn-large" id="Show_Options" style="width:200px">Build Route</button>
                
            }
        </div>
    </center>
</div>


@*----------------------------------------------*@

<div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("SelectModeType", "RandomizedDay")'></div>

<script type="text/javascript">

    $(document).ready(function () {

        $('#Show_Options').click(function () {

            var url = $('#myModal').data('url');
            $.get(url, function (data) {

                $("#myModal").html(data);
                $("#myModal").modal('show');
            });
        });
    });

</script>

DayOut/Views/RandomizedDay/SelectModeType.cshtml

@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container" style="padding-top:10em; width:40% ">
    <div class="row">
        <div class="col-sm-12">
            <div class="modal-content" style="background-color:#f6f5f3; border-radius:75px">
                <div class="modal-header" style="background-color:#f6f5f3; border-radius:75px">
                    <center>
                        <h4 class="modal-title" id="myModal" style="padding-top:20px">Mode</h4>
                    </center>
                    <div>
                        <div class="modal-body" style="background-color:#f6f5f3; border-radius:75px">
                            <center>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div style="float:right">
                                            @Html.ActionLink("Normal", "BuildRoute", "RandomizedDay", null, new { @class = "btn btn-success btn-large", style = "width:200px" })
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div style="float:left">
                                            @Html.ActionLink("Surprise", "Surprise", "RandomizedDay", null, new { @class = "btn btn-success btn-large", style = "width:200px" })
                                        </div>
                                    </div>
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DayOut/Views/RandomizedDay/SelectStartEndTime.cshtml
@model DayOut.Models.SelectTimesViewModel
@{
    ViewData["Title"] = "SelectStartEndTime";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
@*<h2>SelectStartEndTime</h2>

    <div class="row">
        <div class="col-md-12">
            <form asp-action="SelectStartEndTime">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Customer.RandStartTime" class="control-label"></label>
                    <select asp-for="Customer.RandStartTime" class="form-control" asp-items="ViewBag.Time"></select>
                </div>
                <div class="form-group">
    <a href="~/Views/RandomizedDay/LoadingGif.cshtml">~/Views/RandomizedDay/LoadingGif.cshtml</a>
                    <label asp-for="Customer.RandEndTime" class="control-label"></label>
                    <select asp-for="Customer.RandEndTime" class="form-control" asp-items="ViewBag.Time"></select>
                </div>
                @Html.HiddenFor(model => model.AllCategoriesWithPlaceDetails)
                <input type="submit" id="Load_Gif" value="Submit" class="btn btn-default" />
            </form>
        </div>
    </div>*@
<center>
    <div style="padding-bottom:1em">
        <h2>Choose Start and End Times</h2>
        <hr />
    </div>
</center>
<div class="row">
    <div class="col-md-6">
        <div style="float:right">
            <h3>Starting Time</h3>
        </div>
    </div>
    <div class="col-md-6">
        <div style="float:left; padding-top:1em">
            <form asp-action="SelectStartEndTime">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <select asp-for="Customer.RandStartTime" class="form-control" asp-items="ViewBag.Time"></select>
                </div>
                <div class="form-group">
                    <select asp-for="Customer.RandEndTime" class="form-control" asp-items="ViewBag.Time"></select>
                </div>
        </div>
    </div>
</div>
<br />
<center>
    <input type="submit" id="Load_Gif" value="Submit" class="btn btn-primary" style="width:10em" />
</center>
           </form>
@*----------------------------------------------*@
<div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("LoadingGif", "RandomizedDay")'></div>
<script type="text/javascript">

    $(document).ready(function () {

        $('#Load_Gif').click(function () {

            var url = $('#myModal').data('url');
            $.get(url, function (data) {

                $("#myModal").html(data);
                $("#myModal").modal('show');
            });
        });
    });
 </script>

DayOut/Views/RandomizedDay/Surprise.cshtml
@model DayOut.Models.DisplayRouteViewModel
@{
    ViewData["Title"] = "Surprise";
}
<style>

    #map {
        height: 800px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }

    .table_scroll {
        width: 100%;
        overflow-y: scroll;
        border-collapse: collapse;
        border-spacing: 0;
        height: 230px;
        display: block;
    }

    #rcorners2 {
        border-radius: 25px;
        border: 2px solid black;
        padding: 20px;
    }
</style>
<div class="row" style="padding-top:1em">
    <div class="col-md-4">
        <center>
            <div>
                <table class="table_scroll" style="height:650px;">
                    @for (int i = 0; i < Model.Places.Count; i++)
                    {
                        <tr>
                            <td style=" padding-top:1em; padding-right:1em">
                                <div class="row" style="padding-right:1em">
                                    <div class="col-md-2" style="padding:0.5em">
                                        <center>
                                            <h3><strong>@Html.Raw(Model.PlaceLetters[i])</strong></h3>
                                        </center>
                                    </div>
                                    @if (i == 0)
                                    {
                                        <div class="col-md-10" id="rcorners2" style="padding:0.5em">
                                            <span style="font-size:25px"><strong>@Html.Raw(Model.Places[i].Name)</strong></span>
                                            <br />
                                            <span style="font-size:15px">Address: @Html.Raw(Model.Places[i].Address)</span>
                                            <br />
                                            <span style="font-size:15px">Phone: @Html.Raw(Model.Places[i].PhoneNumber)</span>
                                            <br />
                                            <span style="font-size:15px">Rating: @Html.Raw(Model.Places[i].Rating)</span>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="col-md-10" id="rcorners2" style="padding:0.5em">
                                            <center>
                                                <h3><strong>Mystery Location</strong></h3>
                                                <h4>(Revealed 30 min before departure!)</h4>
                                            </center>
                                        </div>
                                    }
                                </div>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </center>
    </div>
    <div class="col-md-8">
        <center>
            <div>
                <div id="map" style="height:650px;"></div>
            </div>
        </center>
    </div>
</div>
<script>
    // Initialize and add the map
    function initMap() {
        // The location of Uluru
        var uluru = { lat: @Html.Raw(Model.Places[0].Latitude), lng: @Html.Raw(Model.Places[0].Longitude) };
        // The map, centered at Uluru
        var map = new google.maps.Map(
            document.getElementById('map'), { zoom: 14, center: uluru });
        // The marker, positioned at Uluru
        var marker = new google.maps.Marker({ position: uluru, map: map });
    }
</script>
<!--Load the API from the specified URL
* The async attribute allows the browser to render the page while the API loads
* The key parameter will contain your own API key (which is not needed for this tutorial)
* The callback parameter executes the initMap() function
-->
<script async defer
         src="https://maps.googleapis.com/maps/api/js?key=@Html.Raw(Model.GoogleAPI)&callback=initMap">
</script>