DayOut/Models/BuildDayViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DayOut.Models
{
    public class BuildDayViewModel
    {
        public Customer Customer { get; set; }
        public int? NextTime { get; set; }
        public string TimeDisplay { get; set; }
    }
}

DayOut/Models/DisplayRouteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DayOut.Models
{
    public class DisplayRouteViewModel
    {
        public List<Place> Places { get; set; }
        public List<string> Addresses { get; set; }
        public List<string> Times { get; set; }
        public string GoogleAPI { get; set; }
        public List<string> PlaceLetters { get; set; }
    }
}

DayOut/Controllers/StructuredDayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DayOut.Class;
using DayOut.Data;
using DayOut.Models;
using GoogleCategories;
using GooglePlaceDetails;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DayOut.Controllers
{
    public class StructuredDayController : Controller
    {
        public ApplicationDbContext db;
        public StructuredDayController(ApplicationDbContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BuildDay()
        {
            DateTime currentTime = DateTime.Now;
            string militaryTime = currentTime.ToString("HHmm");
            int currentMilTime = Convert.ToInt32(militaryTime);
            //ViewData["Time"] = new SelectList(db.Times, "Id", "StandardTime");
            ViewData["Time"] = new SelectList(db.Times.Where(t => t.MilitaryTime > currentMilTime - 100), "Id", "StandardTime");
            return View();
        }
        [HttpPost]
        public IActionResult BuildDay(Customer customer)
        {
            int startTime = db.Times.Where(t => t.Id == customer.StructStartTime).Select(t => t.MilitaryTime).Single();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customerToUpdate = db.Customers.Where(c => c.UserId == userId).Single();
            customerToUpdate.StructStartTime = startTime;
            db.SaveChanges();
            TruncateSelectedTable();
            TruncateSelectedTimesTable();
            return RedirectToAction("SelectCategoriesStructured");
        }
        private void TruncateSelectedTable()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE [SelectedCategories]");
        }
        private void TruncateSelectedTimesTable()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE [SelectedTimes]");
        }
        private void TruncatePlacesTable()
        {
            db.Database.ExecuteSqlCommand("TRUNCATE TABLE [Places]");
        }
        private void SetCategoriesTable(List<string> availableCategories)
        {
            List<Category> allCategories = db.Categories.ToList();
            bool fired = false;
            foreach (Category category in allCategories)
            {
                foreach (string name in availableCategories)
                {
                    if (category.Name == name)
                    {
                        category.IsAvailable = true;
                        db.SaveChanges();
                        fired = true;
                        break;
                    }
                }
                if (fired != true)
                {
                    category.IsAvailable = false;
                    db.SaveChanges();
                }
                fired = false;
            }
        }
        public IActionResult SelectCategoriesStructured(string selected = "")
        {
            
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            int nextTime = customer.StructStartTime;
            SelectCategoriesViewModel selectCategoriesViewModel = new SelectCategoriesViewModel();
            selectCategoriesViewModel.PlaceTime = db.SelectedTimes.Select(t => t.TimeLabel).ToList();
            if (selectCategoriesViewModel.PlaceTime.Count == 0)
            {
                SelectedTimes selectedTime = new SelectedTimes();
                selectedTime.Time = db.Times.Where(t => t.MilitaryTime == customer.StructStartTime).Select(t => t.MilitaryTime).Single();
                selectedTime.TimeLabel = db.Times.Where(t => t.MilitaryTime == customer.StructStartTime).Select(t => t.StandardTime).Single();
                db.SelectedTimes.Add(selectedTime);
                db.SaveChanges();
            }
            int maxId = db.SelectedTimes.Max(t => t.Id); //Get max Id in selected times
            int lastTime = db.SelectedTimes.Where(t => t.Id == maxId).Select(t => t.Time).Single(); // Use max Id to get string of last time
            if (selected != "")
            {
                Category category = db.Categories.Where(c => c.Name == selected).Single();
                SelectedTimes selectedTime = new SelectedTimes();
                int currentId = db.Times.Where(t => t.MilitaryTime == lastTime).Select(t => t.Id).Single(); // Get the current Id of Times table where time name matches last time
                int nextTimeId = currentId + category.IncramentAmount;
                nextTimeId = nextTimeId > 48 ? (nextTimeId - 48) : nextTimeId;
                selectedTime.Time = db.Times.Where(t => t.Id == nextTimeId).Select(t => t.MilitaryTime).Single();
                nextTime = db.Times.Where(t => t.Id == nextTimeId).Select(t => t.MilitaryTime).Single();
                selectedTime.TimeLabel = db.Times.Where(t => t.Id == nextTimeId).Select(t => t.StandardTime).Single();// Set new time to add equal to the time after category completion
                db.SelectedTimes.Add(selectedTime);
                db.SaveChanges();
            }
            List<CategoryPlaces> availableCategories = GetCategoriesAvailable.CategoriesAvailable(customer);
            List<Tuple<List<PlaceDetails>, string>> data = GetAllDetails.ReplaceWithDetails(availableCategories);
            List<Tuple<List<PlaceDetails>, string>> finalData = FilterPlacesOpen.ReturnFilteredPlaces(data, nextTime, nextTime + 300);
            List<string> categories = SetAllCategories.FindAllCategories(finalData);
            SetCategoriesTable(categories);
            if (selected != "")
            {
                SelectedCategory selectedCategory = new SelectedCategory() { Name = selected };
                db.SelectedCategories.Add(selectedCategory);
                Category category = db.Categories.Where(c => c.Name == selected).Single();
                if (category.Name != "Restaurant")
                {
                    category.IsAvailable = false;
                }
                db.SaveChanges();
            }
            selectCategoriesViewModel.PlaceTime = db.SelectedTimes.Select(t => t.TimeLabel).ToList();
            selectCategoriesViewModel.Categories = db.Categories.Where(c => c.IsAvailable == true).Select(c => c.Name).ToList();
            selectCategoriesViewModel.Selected = db.SelectedCategories.Select(c => c.Name).ToList();
            ViewBag.OptionsLeft = selectCategoriesViewModel.Categories.Count > 0 ? true : false;
            ViewBag.HasSelected = selectCategoriesViewModel.Selected.Count > 0 ? true : false;
            return View(selectCategoriesViewModel);
        }

        public IActionResult DisplayRoute(bool fromSelect = true)
        {
            if (fromSelect)
            {
                SetPlaces();
            }
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            if (fromSelect == false)
            {
                if (customer.HasRoute == false)
                {
                    return RedirectToAction("Index", "Home", new { hasroute = false });
                }
            }
            DisplayRouteViewModel displayRoute = new DisplayRouteViewModel();
            displayRoute.Places = db.Places.Where(p => p.CustomerId == customer.Id).ToList();
            displayRoute.Addresses = new List<string>();
            displayRoute.GoogleAPI = APIKey.GoogleAPI;
            displayRoute.Times = db.SelectedTimes.Select(t => t.TimeLabel).ToList();
            displayRoute.Times.Add("End");
            foreach (Place place in displayRoute.Places)
            {
                displayRoute.Addresses.Add(place.Address);
            }
            displayRoute.PlaceLetters = new List<string>() { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M" };
            customer.HasRoute = true;
            customer.StructuredMode = true;
            customer.RandomizedMode = false;
            customer.SurpriseMode = false;
            db.SaveChanges();
            return View(displayRoute);
        }

        private void SetPlaces()
        {
            TruncatePlacesTable();
            List<string> selectedCategories = db.SelectedCategories.Select(c => c.Name).ToList();
            List<int> times = db.SelectedTimes.Select(t => t.Time).ToList();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            Customer customer = db.Customers.Where(c => c.UserId == userId).Single();
            for (int i = 0; i < selectedCategories.Count; i++)
            {
                List<string> catName = new List<string>();
                catName.Add(selectedCategories[i]);
                List<CategoryPlaces> availableCategories = GetCategoriesAvailable.CategoriesAvailable(customer, catName);
                List<Tuple<List<PlaceDetails>, string>> data = GetAllDetails.ReplaceWithDetails(availableCategories);
                List<Tuple<List<PlaceDetails>, string>> finalData = FilterPlacesOpen.ReturnFilteredPlaces(data, times[i], times[i] + 300);
                CheckForPlace(finalData, customer);
            }
        }

        public bool CheckForPlace(List<Tuple<List<PlaceDetails>, string>> finalData, Customer customer)
        {
            foreach (Tuple<List<PlaceDetails>, string> category in finalData)
            {
                List<Place> allPlacesSet = db.Places.ToList();

DayOut/Views/StructuredDay/BuildDay.cshtml
@model DayOut.Models.BuildDayViewModel
@{
    ViewData["Title"] = "BuildDay";
}

<center>
    <div style="padding-bottom:1em">
        <h2>Choose Start Time</h2>
        <hr />
    </div>
</center>

<div class="row">
    <div class="col-md-6">
        <div style="float:right">
            <h3>Starting Time</h3>
        </div>
    </div>
    <div class="col-md-6">
        <div style="float:left; padding-top:1em">
            <form asp-action="BuildDay">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <select asp-for="Customer.StructStartTime" class="form-control" asp-items="ViewBag.Time"></select>
                </div>
        </div>
    </div>
</div>
<br />
<center>
    <input type="submit" value="Submit" class="btn btn-primary" style="width:10em" />
</center>
            </form>


DayOut/Views/StructuredDay/DisplayRoute.cshtml
@model DayOut.Models.DisplayRouteViewModel
@{
    ViewData["Title"] = "DisplayRoute";
}


<!--The div element for the map -->

<style>
    #map {
        height: 800px; /* The height is 400 pixels */
        width: 100%; /* The width is the width of the web page */
    }
    .table_scroll {
        width: 100%;
        overflow-y: scroll;
        border-collapse: collapse;
        border-spacing: 0;
        height: 230px;
        display: block;
    }
    #rcorners2 {
        border-radius: 25px;
        border: 2px solid black;
        padding: 20px;
    }
</style>
<div class="row" style="padding-top:1em">
    <div class="col-md-4">
        <center>
            <div>
                <table class="table_scroll" style="height:650px;">
                    @for (int i = 0; i < Model.Places.Count; i++)
                    {
                        <tr>
                            <td style=" padding-top:1em; padding-right:1em">
                                <div class="row" style="padding-right:1em">
                                    <div class="col-md-2" style="padding:0.5em">
                                        <center>
                                            <h3><strong>@Html.Raw(Model.PlaceLetters[i])</strong></h3>
                                        </center>
                                    </div>
                                    <div class="col-md-10" id="rcorners2" style="padding:0.5em">
                                        <span style="font-size:25px"><strong>@Html.Raw(Model.Places[i].Name)</strong></span>
                                        <br />
                                        <span style="font-size:15px">Address: @Html.Raw(Model.Places[i].Address)</span>
                                        <br />
                                        <span style="font-size:15px">Phone: @Html.Raw(Model.Places[i].PhoneNumber)</span>
                                        <br />
                                        <span style="font-size:15px">Rating: @Html.Raw(Model.Places[i].Rating)</span>
                                        <br />
                                        <span style="font-size:15px">Category: @Html.Raw(Model.Places[i].Category)</span>
                                        <br />
                                        <span style="font-size:15px">Time of Arrival:<strong> @Html.Raw(Model.Times[i])</strong></span>
                                    </div>
                                </div>

                            </td>
                        </tr>
                    }
                </table>
            </div>
        </center>
    </div>
    <div class="col-md-8">
        <center>
            <div>
                <div id="map"  style="height:650px;"></div>
            </div>
        </center>
    </div>
</div>

<div hidden>
    <div>
        <select id="start">
            <option value=@Html.Raw(Model.Addresses[0])>Halifax, NS</option>
        </select>
        <select multiple id="waypoints">
            @for (int i = 1; i < Model.Addresses.Count - 1; i++)
            {
                <option value=@Html.Raw(Model.Addresses[i])></option>
            }
        </select>
        <select id="end">
            <option value=@Html.Raw(Model.Addresses[Model.Addresses.Count - 1])>Vancouver, BC</option>
        </select>
    </div>
    <div id="directions-panel"></div>
</div>

<script type="text/javascript">
    function initMap() {
        var directionsService = new google.maps.DirectionsService;
        var directionsDisplay = new google.maps.DirectionsRenderer;
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 6,
            center: { lat: 41.85, lng: -87.65 }
        });
        directionsDisplay.setMap(map);
        calculateAndDisplayRoute(directionsService, directionsDisplay);
    }

    function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        var waypts = [];
        @*var pre = '@Html.Raw(Json.Serialize(Model.Addresses))';
        var checkboxArrayTest = JSON.parse(pre);
        var checkboxArrayHard = ["montreal, quebec", "toronto, ont"];*@
        var checkboxArray = document.getElementById('waypoints');;
        for (var i = 0; i < checkboxArray.length; i++) {
            waypts.push({
                location: checkboxArray[i].value,
                stopover: true
            });

        }

        directionsService.route({
            origin: document.getElementById('start').value,
            destination: document.getElementById('end').value,
            waypoints: waypts,
            optimizeWaypoints: true,
            travelMode: 'DRIVING'
        }, function (response, status) {
            if (status === 'OK') {
                directionsDisplay.setDirections(response);
                var route = response.routes[0];
                var summaryPanel = document.getElementById('directions-panel');
                summaryPanel.innerHTML = '';
                 //For each route, display summary information.
                //for (var i = 0; i < route.legs.length; i++) {
                //    var routeSegment = i + 1;
                //    summaryPanel.innerHTML += '<b>Route Segment: ' + routeSegment +
                //        '</b><br>';
                //    summaryPanel.innerHTML += route.legs[i].start_address + ' to ';
                //    summaryPanel.innerHTML += route.legs[i].end_address + '<br>';
                //    summaryPanel.innerHTML += route.legs[i].distance.text + '<br><br>';
                //}
            } else {
                window.alert('Directions request failed due to ' + status);
            }
        }
                );
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=@Html.Raw(Model.GoogleAPI)&callback=initMap">
</script>

DayOut/Views/StructuredDay/LoadingGif.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="container" style="padding-top:10em; width:30% ">
    <div class="row">
        <div class="col-sm-12">
            <div class="modal-content" style="background-color:#f6f5f3; border-radius:75px">
                <div class="modal-header" style="background-color:#f6f5f3; border-radius:75px">
                    <center>
                        <h4 class="modal-title" id="myModal" style="padding-top:20px">Finding Places Open</h4>
                    </center>
                    <div>
                        <div class="modal-body" style="background-color:#f6f5f3; border-radius:75px">
                            <center>
                                <div>
                                    <img  style="height:15em; width:15em" src="https://cdn-images-1.medium.com/max/1600/0*smsSMhaW2J5RgY8G.gif" />
                                </div>
                            </center>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DayOut/Views/StructuredDay/SelectCategoriesStructured.cshtml
@model DayOut.Models.SelectCategoriesViewModel
@{
    ViewData["Title"] = "SelectCategoriesStructured";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div style="padding-top:3em">
    <center>
        @if (ViewBag.HasSelected == true)
        {
            <h2>Day Plan</h2>
            <hr />
            <table>
                <tr></tr>
                @for (int i = 0; i < Model.Selected.Count; i++)
                {
                    <tr>
                        <td>
                            <div class="row">
                                <div class="col-md-2">
                                    <div style="padding-top:1em">
                                        <div style="border:1px solid black; float:right; width:120px; border-radius:75px">
                                            <center>
                                                <h3>@Html.Raw(Model.PlaceTime[i])</h3>
                                            </center>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div style="padding-top:2em">
                                        <center>
                                            <button class="btn btn-default btn-large" id="Load_Gif" style="width:200px">@Html.Raw(Model.Selected[i])</button>
                                        </center>
                                    </div>
                                </div>
   
                            </div>
                        </td>
                    </tr>
                }
            </table>
        }
        @if (ViewBag.OptionsLeft == true)
        {
            <h2>Select a Category</h2>
            <hr />
            <div>
                <table>
                    <tr></tr>
                    @foreach (var item in Model.Categories)
                    {
                        if (item != null)
                        {
                            <tr>
                                <td>
                                    @Html.ActionLink(item, "SelectCategoriesStructured", "StructuredDay", new { selected = item }, new { @class = "btn btn-primary btn-large", style = "width:200px" })
                                </td>
                            </tr>
                        }
                    }
                </table>
                <div hidden>
                    @Html.EditorFor(model => model.Categories)
                </div>
            </div>
        }
            <div>
                <br />
                @if (ViewBag.OptionsLeft == false)
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div style="float:right">
                                @Html.ActionLink("Build Day", "DisplayRoute", "StructuredDay", null, new { @class = "btn btn-success btn-large", style = "width:200px" })

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div style="float:left">
                                @Html.ActionLink("Restart", "BuildDay", "StructuredDay", null, new { @class = "btn btn-primary btn-large", style = "width:200px" })
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    @Html.ActionLink("Build Day", "DisplayRoute", "StructuredDay", null, new { @class = "btn btn-success btn-large", style = "width:200px" })
                }
            </div>
    </center>
</div>


@*----------------------------------------------*@

<div class="modal fade" id="myModal" role="dialog" data-url='@Url.Action("LoadingGif", "StructuredDay")'></div>

<script type="text/javascript">

    $(document).ready(function () {

        $('#Load_Gif').click(function () {

            var url = $('#myModal').data('url');
            $.get(url, function (data) {

                $("#myModal").html(data);
                $("#myModal").modal('show');
            });
        });
    });

</script>